// Mocks generated by Mockito 5.4.6 from annotations
// in Nutricional/test/integration/helpers/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i29;
import 'dart:typed_data' as _i31;

import 'package:cloud_firestore/cloud_firestore.dart' as _i10;
import 'package:connectivity_plus/connectivity_plus.dart' as _i30;
import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i8;
import 'package:firebase_core/firebase_core.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i27;
import 'package:Nutricional/data/datasources/calendar_firebase_datasource.dart'
    as _i22;
import 'package:Nutricional/data/datasources/cloudinary_datasource.dart'
    as _i28;
import 'package:Nutricional/data/datasources/local/calendar_local_datasource.dart'
    as _i25;
import 'package:Nutricional/data/datasources/local/database_helper.dart'
    as _i26;
import 'package:Nutricional/data/datasources/local/product_local_datasource.dart'
    as _i24;
import 'package:Nutricional/data/datasources/local/recipe_local_datasource.dart'
    as _i23;
import 'package:Nutricional/data/datasources/product_firebase_datasource.dart'
    as _i21;
import 'package:Nutricional/data/datasources/recipe_firebase_datasource.dart'
    as _i20;
import 'package:Nutricional/data/services/connectivity_service.dart' as _i16;
import 'package:Nutricional/data/services/notification_service.dart' as _i18;
import 'package:Nutricional/data/services/open_food_facts_service.dart' as _i19;
import 'package:Nutricional/data/services/sync_service.dart' as _i17;
import 'package:Nutricional/domain/entities/calendar_entry.dart' as _i5;
import 'package:Nutricional/domain/entities/product.dart' as _i3;
import 'package:Nutricional/domain/entities/recipe.dart' as _i4;
import 'package:Nutricional/domain/entities/user.dart' as _i2;
import 'package:Nutricional/domain/repositories/auth_repository.dart' as _i12;
import 'package:Nutricional/domain/repositories/calendar_repository.dart'
    as _i15;
import 'package:Nutricional/domain/repositories/product_repository.dart'
    as _i13;
import 'package:Nutricional/domain/repositories/recipe_repository.dart' as _i14;
import 'package:sqflite/sqflite.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipe_2 extends _i1.SmartFake implements _i4.Recipe {
  _FakeRecipe_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCalendarEntry_3 extends _i1.SmartFake implements _i5.CalendarEntry {
  _FakeCalendarEntry_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_4 extends _i1.SmartFake implements _i6.Database {
  _FakeDatabase_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_5 extends _i1.SmartFake implements _i7.FirebaseApp {
  _FakeFirebaseApp_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_6 extends _i1.SmartFake
    implements _i8.ActionCodeInfo {
  _FakeActionCodeInfo_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_7 extends _i1.SmartFake
    implements _i9.UserCredential {
  _FakeUserCredential_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_8 extends _i1.SmartFake
    implements _i9.ConfirmationResult {
  _FakeConfirmationResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordValidationStatus_9 extends _i1.SmartFake
    implements _i8.PasswordValidationStatus {
  _FakePasswordValidationStatus_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_10 extends _i1.SmartFake implements _i10.Settings {
  _FakeSettings_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_11<T extends Object?> extends _i1.SmartFake
    implements _i10.CollectionReference<T> {
  _FakeCollectionReference_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_12 extends _i1.SmartFake implements _i10.WriteBatch {
  _FakeWriteBatch_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_13 extends _i1.SmartFake
    implements _i10.LoadBundleTask {
  _FakeLoadBundleTask_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_14<T1 extends Object?> extends _i1.SmartFake
    implements _i10.QuerySnapshot<T1> {
  _FakeQuerySnapshot_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_15<T extends Object?> extends _i1.SmartFake
    implements _i10.Query<T> {
  _FakeQuery_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_16<T extends Object?> extends _i1.SmartFake
    implements _i10.DocumentReference<T> {
  _FakeDocumentReference_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_17<T1> extends _i1.SmartFake implements _i11.Future<T1> {
  _FakeFuture_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineSource_18 extends _i1.SmartFake
    implements _i10.PipelineSource {
  _FakePipelineSource_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.User> loginWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmail, [email, password]),
            returnValue: _i11.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#loginWithEmail, [email, password]),
              ),
            ),
          )
          as _i11.Future<_i2.User>);

  @override
  _i11.Future<_i2.User> registerWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [
              email,
              password,
              displayName,
            ]),
            returnValue: _i11.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#registerWithEmail, [
                  email,
                  password,
                  displayName,
                ]),
              ),
            ),
          )
          as _i11.Future<_i2.User>);

  @override
  _i11.Future<_i2.User> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i11.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#loginWithGoogle, [])),
            ),
          )
          as _i11.Future<_i2.User>);

  @override
  _i11.Future<_i2.User> loginWithFacebook() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithFacebook, []),
            returnValue: _i11.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#loginWithFacebook, [])),
            ),
          )
          as _i11.Future<_i2.User>);

  @override
  _i11.Future<_i2.User> loginWithApi(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithApi, [email, password]),
            returnValue: _i11.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#loginWithApi, [email, password]),
              ),
            ),
          )
          as _i11.Future<_i2.User>);

  @override
  _i11.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<_i2.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i11.Stream<_i2.User?>.empty(),
          )
          as _i11.Stream<_i2.User?>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i13.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.Product> createProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i11.Future<_i3.Product>.value(
              _FakeProduct_1(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i11.Future<_i3.Product>);

  @override
  _i11.Future<List<_i3.Product>> getProductsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByUser, [userId]),
            returnValue: _i11.Future<List<_i3.Product>>.value(<_i3.Product>[]),
          )
          as _i11.Future<List<_i3.Product>>);

  @override
  _i11.Future<_i3.Product?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i11.Future<_i3.Product?>.value(),
          )
          as _i11.Future<_i3.Product?>);

  @override
  _i11.Future<_i3.Product?> getProductByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByBarcode, [barcode]),
            returnValue: _i11.Future<_i3.Product?>.value(),
          )
          as _i11.Future<_i3.Product?>);

  @override
  _i11.Future<void> updateProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i14.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i4.Recipe> createRecipe(_i4.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#createRecipe, [recipe]),
            returnValue: _i11.Future<_i4.Recipe>.value(
              _FakeRecipe_2(this, Invocation.method(#createRecipe, [recipe])),
            ),
          )
          as _i11.Future<_i4.Recipe>);

  @override
  _i11.Future<List<_i4.Recipe>> getRecipesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesByUser, [userId]),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<List<_i4.Recipe>> getAllRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecipes, []),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<_i4.Recipe> getRecipeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [id]),
            returnValue: _i11.Future<_i4.Recipe>.value(
              _FakeRecipe_2(this, Invocation.method(#getRecipeById, [id])),
            ),
          )
          as _i11.Future<_i4.Recipe>);

  @override
  _i11.Future<void> updateRecipe(_i4.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecipe, [recipe]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteRecipe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecipe, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i15.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.CalendarEntry> createEntry(_i5.CalendarEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#createEntry, [entry]),
            returnValue: _i11.Future<_i5.CalendarEntry>.value(
              _FakeCalendarEntry_3(
                this,
                Invocation.method(#createEntry, [entry]),
              ),
            ),
          )
          as _i11.Future<_i5.CalendarEntry>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByUser, [userId]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<_i5.CalendarEntry> getEntryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryById, [id]),
            returnValue: _i11.Future<_i5.CalendarEntry>.value(
              _FakeCalendarEntry_3(
                this,
                Invocation.method(#getEntryById, [id]),
              ),
            ),
          )
          as _i11.Future<_i5.CalendarEntry>);

  @override
  _i11.Future<void> updateEntry(_i5.CalendarEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateEntry, [entry]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> syncAllFromCloud(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllFromCloud, [userId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i16.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Stream<bool> get connectionStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStream),
            returnValue: _i11.Stream<bool>.empty(),
          )
          as _i11.Stream<bool>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> checkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnection, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i17.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  void startAutoSync({Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(#startAutoSync, [], {#interval: interval}),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoSync() => super.noSuchMethod(
    Invocation.method(#stopAutoSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> syncAll() =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> syncRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#syncRecipes, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> downloadRecipesForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadRecipesForUser, [userId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> forceSyncNow() =>
      (super.noSuchMethod(
            Invocation.method(#forceSyncNow, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<int> getPendingSyncCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncCount, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i18.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> scheduleNotification(_i5.CalendarEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNotification, [entry]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> cancelNotification(String? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [entryId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> areNotificationsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#areNotificationsEnabled, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}

/// A class which mocks [OpenFoodFactsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenFoodFactsService extends _i1.Mock
    implements _i19.OpenFoodFactsService {
  MockOpenFoodFactsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.Product?> getProductByBarcode(
    String? barcode,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByBarcode, [barcode, userId]),
            returnValue: _i11.Future<_i3.Product?>.value(),
          )
          as _i11.Future<_i3.Product?>);
}

/// A class which mocks [RecipeFirebaseDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeFirebaseDatasource extends _i1.Mock
    implements _i20.RecipeFirebaseDatasource {
  MockRecipeFirebaseDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i4.Recipe> createRecipe(_i4.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#createRecipe, [recipe]),
            returnValue: _i11.Future<_i4.Recipe>.value(
              _FakeRecipe_2(this, Invocation.method(#createRecipe, [recipe])),
            ),
          )
          as _i11.Future<_i4.Recipe>);

  @override
  _i11.Future<List<_i4.Recipe>> getRecipesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesByUser, [userId]),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<List<_i4.Recipe>> getAllRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecipes, []),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<_i4.Recipe> getRecipeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [id]),
            returnValue: _i11.Future<_i4.Recipe>.value(
              _FakeRecipe_2(this, Invocation.method(#getRecipeById, [id])),
            ),
          )
          as _i11.Future<_i4.Recipe>);

  @override
  _i11.Future<void> updateRecipe(_i4.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecipe, [recipe]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteRecipe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecipe, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [ProductFirebaseDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductFirebaseDatasource extends _i1.Mock
    implements _i21.ProductFirebaseDatasource {
  MockProductFirebaseDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.Product> createProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i11.Future<_i3.Product>.value(
              _FakeProduct_1(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i11.Future<_i3.Product>);

  @override
  _i11.Future<List<_i3.Product>> getProductsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByUser, [userId]),
            returnValue: _i11.Future<List<_i3.Product>>.value(<_i3.Product>[]),
          )
          as _i11.Future<List<_i3.Product>>);

  @override
  _i11.Future<_i3.Product> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i11.Future<_i3.Product>.value(
              _FakeProduct_1(this, Invocation.method(#getProductById, [id])),
            ),
          )
          as _i11.Future<_i3.Product>);

  @override
  _i11.Future<void> updateProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [CalendarFirebaseDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarFirebaseDatasource extends _i1.Mock
    implements _i22.CalendarFirebaseDatasource {
  MockCalendarFirebaseDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.CalendarEntry> createEntry(_i5.CalendarEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#createEntry, [entry]),
            returnValue: _i11.Future<_i5.CalendarEntry>.value(
              _FakeCalendarEntry_3(
                this,
                Invocation.method(#createEntry, [entry]),
              ),
            ),
          )
          as _i11.Future<_i5.CalendarEntry>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByUser, [userId]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<_i5.CalendarEntry> getEntryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryById, [id]),
            returnValue: _i11.Future<_i5.CalendarEntry>.value(
              _FakeCalendarEntry_3(
                this,
                Invocation.method(#getEntryById, [id]),
              ),
            ),
          )
          as _i11.Future<_i5.CalendarEntry>);

  @override
  _i11.Future<void> updateEntry(_i5.CalendarEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateEntry, [entry]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [RecipeLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeLocalDatasource extends _i1.Mock
    implements _i23.RecipeLocalDatasource {
  MockRecipeLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> saveRecipe(_i4.Recipe? recipe, {bool? synced = false}) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipe, [recipe], {#synced: synced}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i4.Recipe?> getRecipeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [id]),
            returnValue: _i11.Future<_i4.Recipe?>.value(),
          )
          as _i11.Future<_i4.Recipe?>);

  @override
  _i11.Future<List<_i4.Recipe>> getRecipesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesByUser, [userId]),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<List<_i4.Recipe>> getAllRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecipes, []),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<void> updateRecipe(_i4.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecipe, [recipe]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteRecipe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecipe, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> hardDeleteRecipe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteRecipe, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i4.Recipe>> getUnsyncedRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedRecipes, []),
            returnValue: _i11.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
          )
          as _i11.Future<List<_i4.Recipe>>);

  @override
  _i11.Future<List<String>> getDeletedUnsyncedRecipeIds() =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedUnsyncedRecipeIds, []),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);

  @override
  _i11.Future<void> markAsSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> saveRecipesFromCloud(List<_i4.Recipe>? recipes) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipesFromCloud, [recipes]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<int> countRecipesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#countRecipesByUser, [userId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [ProductLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDatasource extends _i1.Mock
    implements _i24.ProductLocalDatasource {
  MockProductLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> saveProduct(_i3.Product? product, {bool? synced = false}) =>
      (super.noSuchMethod(
            Invocation.method(#saveProduct, [product], {#synced: synced}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i3.Product?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i11.Future<_i3.Product?>.value(),
          )
          as _i11.Future<_i3.Product?>);

  @override
  _i11.Future<_i3.Product?> getProductByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByBarcode, [barcode]),
            returnValue: _i11.Future<_i3.Product?>.value(),
          )
          as _i11.Future<_i3.Product?>);

  @override
  _i11.Future<List<_i3.Product>> getProductsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByUser, [userId]),
            returnValue: _i11.Future<List<_i3.Product>>.value(<_i3.Product>[]),
          )
          as _i11.Future<List<_i3.Product>>);

  @override
  _i11.Future<List<_i3.Product>> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i11.Future<List<_i3.Product>>.value(<_i3.Product>[]),
          )
          as _i11.Future<List<_i3.Product>>);

  @override
  _i11.Future<void> updateProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> hardDeleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteProduct, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i3.Product>> getUnsyncedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedProducts, []),
            returnValue: _i11.Future<List<_i3.Product>>.value(<_i3.Product>[]),
          )
          as _i11.Future<List<_i3.Product>>);

  @override
  _i11.Future<void> markAsSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> saveProductsFromCloud(List<_i3.Product>? products) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductsFromCloud, [products]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<String>> getDeletedProductIds() =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedProductIds, []),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);
}

/// A class which mocks [CalendarLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarLocalDatasource extends _i1.Mock
    implements _i25.CalendarLocalDatasource {
  MockCalendarLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> saveEntry(
    _i5.CalendarEntry? entry, {
    bool? synced = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntry, [entry], {#synced: synced}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i5.CalendarEntry?> getEntryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryById, [id]),
            returnValue: _i11.Future<_i5.CalendarEntry?>.value(),
          )
          as _i11.Future<_i5.CalendarEntry?>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByDate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByDate, [userId, date]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getEntriesByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesByUser, [userId]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<void> updateEntry(_i5.CalendarEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateEntry, [entry]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> hardDeleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteEntry, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getUnsyncedEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedEntries, []),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);

  @override
  _i11.Future<void> markAsSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> saveEntriesFromCloud(List<_i5.CalendarEntry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntriesFromCloud, [entries]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<String>> getDeletedEntryIds() =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedEntryIds, []),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);

  @override
  _i11.Future<void> markNotificationSent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationSent, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i5.CalendarEntry>> getPendingNotifications(DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingNotifications, [now]),
            returnValue: _i11.Future<List<_i5.CalendarEntry>>.value(
              <_i5.CalendarEntry>[],
            ),
          )
          as _i11.Future<List<_i5.CalendarEntry>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i26.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i6.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i6.Database>.value(
              _FakeDatabase_4(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i6.Database>);

  @override
  _i11.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String> getDatabasePath() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, []),
            returnValue: _i11.Future<String>.value(
              _i27.dummyValue<String>(
                this,
                Invocation.method(#getDatabasePath, []),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<void> clearAllTables() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllTables, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDatabase, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [CloudinaryDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudinaryDatasource extends _i1.Mock
    implements _i28.CloudinaryDatasource {
  MockCloudinaryDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<String> uploadImage(_i29.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [imageFile]),
            returnValue: _i11.Future<String>.value(
              _i27.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [imageFile]),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<void> deleteImage(String? publicId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [publicId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  String? extractPublicIdFromUrl(String? url) =>
      (super.noSuchMethod(Invocation.method(#extractPublicIdFromUrl, [url]))
          as String?);

  @override
  _i11.Future<void> deleteImageByUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImageByUrl, [url]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i30.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Stream<_i30.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i11.Stream<_i30.ConnectivityResult>.empty(),
          )
          as _i11.Stream<_i30.ConnectivityResult>);

  @override
  _i11.Future<_i30.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i11.Future<_i30.ConnectivityResult>.value(
              _i30.ConnectivityResult.bluetooth,
            ),
          )
          as _i11.Future<_i30.ConnectivityResult>);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i9.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_5(this, Invocation.getter(#app)),
          )
          as _i7.FirebaseApp);

  @override
  set app(_i7.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i11.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i8.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i11.Future<_i8.ActionCodeInfo>.value(
              _FakeActionCodeInfo_6(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i11.Future<_i8.ActionCodeInfo>);

  @override
  _i11.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i9.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Stream<_i9.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i11.Stream<_i9.User?>.empty(),
          )
          as _i11.Stream<_i9.User?>);

  @override
  _i11.Stream<_i9.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i11.Stream<_i9.User?>.empty(),
          )
          as _i11.Stream<_i9.User?>);

  @override
  _i11.Stream<_i9.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i11.Stream<_i9.User?>.empty(),
          )
          as _i11.Stream<_i9.User?>);

  @override
  _i11.Future<void> sendPasswordResetEmail({
    required String? email,
    _i8.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i8.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setPersistence(_i8.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i9.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.UserCredential> signInWithCredential(
    _i8.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.UserCredential> signInWithProvider(
    _i8.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<_i9.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i9.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i11.Future<_i9.ConfirmationResult>.value(
              _FakeConfirmationResult_8(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i11.Future<_i9.ConfirmationResult>);

  @override
  _i11.Future<_i9.UserCredential> signInWithPopup(_i8.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i11.Future<_i9.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i11.Future<_i9.UserCredential>);

  @override
  _i11.Future<void> signInWithRedirect(_i8.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i11.Future<String>.value(
              _i27.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i8.PhoneMultiFactorInfo? multiFactorInfo,
    required _i8.PhoneVerificationCompleted? verificationCompleted,
    required _i8.PhoneVerificationFailed? verificationFailed,
    required _i8.PhoneCodeSent? codeSent,
    required _i8.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i8.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> revokeAccessToken(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#revokeAccessToken, [accessToken]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i8.PasswordValidationStatus> validatePassword(
    _i9.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePassword, [auth, password]),
            returnValue: _i11.Future<_i8.PasswordValidationStatus>.value(
              _FakePasswordValidationStatus_9(
                this,
                Invocation.method(#validatePassword, [auth, password]),
              ),
            ),
          )
          as _i11.Future<_i8.PasswordValidationStatus>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i10.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_5(this, Invocation.getter(#app)),
          )
          as _i7.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i27.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i10.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_10(this, Invocation.getter(#settings)),
          )
          as _i10.Settings);

  @override
  set app(_i7.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i10.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i10.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_11<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
          )
          as _i10.CollectionReference<Map<String, dynamic>>);

  @override
  _i10.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_12(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i10.WriteBatch);

  @override
  _i11.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i10.LoadBundleTask loadBundle(_i31.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_13(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i10.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i10.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i10.GetOptions? options = const _i10.GetOptions(),
    required _i10.FromFirestore<T>? fromFirestore,
    required _i10.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i11.Future<_i10.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_14<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i10.QuerySnapshot<T>>);

  @override
  _i11.Future<_i10.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i10.GetOptions? options = const _i10.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i11.Future<_i10.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_14<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i11.Future<_i10.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i10.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_15<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i10.Query<Map<String, dynamic>>);

  @override
  _i11.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i10.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_16<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
          )
          as _i10.DocumentReference<Map<String, dynamic>>);

  @override
  _i11.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i11.Stream<void>.empty(),
          )
          as _i11.Stream<void>);

  @override
  _i11.Future<T> runTransaction<T>(
    _i10.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i27.ifNotNull(
                  _i27.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i11.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i11.Future<T>);

  @override
  _i11.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i10.PipelineSource pipeline() =>
      (super.noSuchMethod(
            Invocation.method(#pipeline, []),
            returnValue: _FakePipelineSource_18(
              this,
              Invocation.method(#pipeline, []),
            ),
          )
          as _i10.PipelineSource);

  @override
  _i11.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}
